// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: iUser.proto

package local_service_Hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for IUser service

type IUserService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	GetInfo(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
}

type iUserService struct {
	c    client.Client
	name string
}

func NewIUserService(name string, c client.Client) IUserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "demo"
	}
	return &iUserService{
		c:    c,
		name: name,
	}
}

func (c *iUserService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "IUser.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iUserService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "IUser.Register", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iUserService) GetInfo(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.name, "IUser.GetInfo", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IUser service

type IUserHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Register(context.Context, *RegisterRequest, *RegisterResponse) error
	GetInfo(context.Context, *InfoRequest, *InfoResponse) error
}

func RegisterIUserHandler(s server.Server, hdlr IUserHandler, opts ...server.HandlerOption) error {
	type iUser interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		GetInfo(ctx context.Context, in *InfoRequest, out *InfoResponse) error
	}
	type IUser struct {
		iUser
	}
	h := &iUserHandler{hdlr}
	return s.Handle(s.NewHandler(&IUser{h}, opts...))
}

type iUserHandler struct {
	IUserHandler
}

func (h *iUserHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.IUserHandler.Login(ctx, in, out)
}

func (h *iUserHandler) Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.IUserHandler.Register(ctx, in, out)
}

func (h *iUserHandler) GetInfo(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.IUserHandler.GetInfo(ctx, in, out)
}
